### ISSUE TITLE
I18n of interaction potential and phase diagram panels

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#128]
@aadish @arouinfar the sim generally passes `?stringTest=double`. The only areas that could use some attention are these two panels on the Phase Changes screen:

<img width="318" alt="screen shot 2016-06-07 at 12 01 36 pm" src="https://cloud.githubusercontent.com/assets/5863899/15869116/30f671e6-2ca8-11e6-8d05-6ee600ce8066.png">

I'm going to pass this off to @arouinfar to make the relevant decisions. This was checked for phetsims/tasks/issues/609.

Side note: the interaction potential panel gets slightly more cramped when Adjustable Attraction is selected.

<img width="327" alt="screen shot 2016-06-07 at 12 08 03 pm" src="https://cloud.githubusercontent.com/assets/5863899/15869208/9f29d2de-2ca8-11e6-922f-f32c79a3ad53.png">

**Comment by arouinfar** [comment]
There's not much we can do to prevent long strings in this case, but perhaps we can give them a bit more room. 

@aadish let's allow these panels to expand by up to 50px to accommodate long strings. This will alleviate some of the problem for horizontal strings -- there's not really anything we can do about the vertical strings. However, if ONE panel expands to accommodate a string, the others should expand by the same amount to keep the panels the same width. The interaction potential graph and phase diagram do not need to expand. They should instead be centered within the panel.
![image](https://cloud.githubusercontent.com/assets/8419308/15904448/4e6b4c08-2d6e-11e6-8ad8-1e4fca02d5a9.png)


Let's also move the "Distance Between Molecules" label down a few pixels so that it won't overlap the arrow... or move the graph up a little if there isn't room to move the text down.

**Comment by arouinfar** [comment]
> ![image](https://cloud.githubusercontent.com/assets/8419308/15904876/dc4c0462-2d6f-11e6-88df-608167dcd4a4.png)

The sigma and epsilon are unlikely to be translated, and if they are, it's still unlikely that the string will be longer than a character or two. To avoid the situation in the screenshot above, let's scale the sigma string so the text becomes smaller, rather than expanding.

The adjustable attraction slider looks like it has quite a few i18n issues. The strong and weak labels should be allowed to expand further before being scaled down.
![image](https://cloud.githubusercontent.com/assets/8419308/15905110/dbd1fe96-2d70-11e6-9104-4d28dfa574ee.png)



To summarize the i18n changes that @aadish should make:
- [ ] Panels can expand up to 50px to accommodate long strings, but all three panels should maintain the same width. 
- [ ] Interaction potential graph and phase diagram graphic will not expand with the panel. They should be centered within the panel.
- [ ] To avoid "Distance Between Atoms" label from overlapping the arrow, move the interaction potential graph up by a few pixels.
- [ ] Do not allow the sigma string to expand so that it will overlap the axis/curve in the Adjusted Attraction case, scale it down.
- [ ] Slider labels should be allowed to expand to double their size before scaling down the font size.

**Comment by phet-steele** [comment]
@arouinfar, please take a look. I like all these changes; there has certainly been an improvement. My only qualm is this, at weak interaction potential (Adjustable Interaction):
<img width="282" alt="screen shot 2016-06-23 at 2 59 18 pm" src="https://cloud.githubusercontent.com/assets/5863899/16320091/51fe8cc2-3953-11e6-9031-de76f416bc13.png">
The epsilon is slightly covered.

**Comment by arouinfar** [comment]
Good observation @phet-steele!

@aadish can the epsilon be moved a little to the right to avoid this overlap?

**Comment by phet-steele** [comment]
This is something for @jbphet

**Comment by jbphet** [comment]
Fixed the issue noted just above by adding code to limit the number of characters for this label to 1, also moved epsilon to be just above the well since current position does not match Java version and does not make it clear what it represents.  Assigning to @arouinfar to test on master.

**Comment by arouinfar** [comment]
Epsilon location looks great @jbphet!
