### ISSUE TITLE
System remains at absolute zero when pumping in particles to a 0K sample

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#129]
In discussing #117 with @aadish and @jbphet, we discovered another issue related to absolute zero.

If a solid is cooled to absolute zero, the particles will stop moving (as they should). If additional particles are pumped in, the temperature remains 0K, but the solid sample will begin to vibrate once one of the newly pumped in particle collides with it.

![absolutezero2](https://cloud.githubusercontent.com/assets/8419308/15878480/8828065c-2cd8-11e6-9387-1f7e9c77525e.gif)

@jbphet proposed that the temperature of the pumped in particles could be given some value based on its speed (currently they have no associated temperature). Once the particle hits the solid, the solid would begin to vibrate, and the temperature of the system would increase proportionally, based on the relative number of colliding/solid particles. That way the temperature of the system would be >0K when the solid begins to move.

One drawback of this approach would be that the solid may start to vibrate before the collision occurs. However, the current behavior isn't particularly desirable, either. 

@emily-phet do you have any suggestions for how to handle the situation shown in the above .gif?

**Comment by emily-phet** [comment]
I think @ariel-phet would know more about these temperatures...but wouldn't the temperature of the system be above zero once the particles are pumped in? Aside from whether or not the thermometer should read 1 upon pumping in or upon interacting with the stationary particles, I agree with @jbphet 's suggestion.

**Comment by ariel-phet** [comment]
I agree that the moment you pump atoms in and they are moving you have to have a temperature above 0. I suppose if you are getting technical I feel like I could make an argument that the solid could start vibrating before the collision -- any particles in motion will have a finite temperature and therefore be emitting blackbody radiation which could cause heating (even if ever so slight) of the solid. Blackbody radiation I think is sort of an ensemble feature...but still...

**Comment by arouinfar** [comment]
Thanks @emily-phet and @ariel-phet!

The problem is that the model does not assign any temperature to incoming particles, but instead the temperature is derived from other properties of the system. Adding more particles to the container will never change the temperature of the system, so there needs to be an exception for the situation described in this issue.

I am not particularly bothered by the solid vibrating before a collision, given @ariel-phet's explanation. Perhaps @jbphet's idea is the way to go.

In the case where particles are pumped into a system at 0K, the incoming particles will have a temperature derived from their speed. The system temperature will then be recalculated using a weighted average. For example, if two particles are pumped in at 52K, and the 100 other particles in the container are at 0K, the system temperature will raise to 1K. 

How does that sound @ariel-phet?

**Comment by jbphet** [comment]
What @arouinfar described in the comment above is close, but not quite how the model behaves.  The temperature value is actually a parameter that is set within the code.  So, for instance, when the user uses the heater-cooler to add heat to the system, the code gradually increases the temperature.  That's why adding particles currently does not affect the temperature.  What might be possible is to have the code bump the temperature a bit when particles are pumped in, but this may have the undesired side effect of making the other particles start to move before any of the new particles collide with them.  This would be a little weird too, but perhaps better than the current behavior.

**Comment by arouinfar** [comment]
Thanks for the clarification @jbphet!

I think it would be more problematic to show molecular motion at 0K than for the solid to heat up before a collision. In the latter situation we could leverage @ariel-phet's black body radiation explanation. 

I'm tagging this issue with teaching resources, because whatever approach we take will need to be documented in the Teacher Tips.

**Comment by ariel-phet** [comment]
@jbphet yes I think the code should bump the temperature a bit. Temperature is an ensemble average of kinetic energy of a system, so it makes sense to measure it as having increased with pumped in moving particles. In addition, we can ask @dubson opinion, but I think it is valid from a quantum mechanical point of view that you can have these particles start to gain energy before a collision occurs. Certainly if we considered something like a CO2 molecule entering and moving, it could have some vibrational energy and be radiating.

I don't think we could usually think of a single particle as having black body radiation...but once you have a few in there, we can start to consider an ensemble (I think). 

@arouinfar definitely ask Steve Pollock or Mike if we could make a reasonable justification argument in the tips.

**Comment by arouinfar** [comment]
Sounds good @ariel-phet. I'll reach out to Mike and Steve and report back.

**Comment by jbphet** [comment]
I've added code that bumps up the temperature 2 degrees Kelvin if the user pumps in particles while at absolute zero.  This works reasonably well, but is very much a special case.  I tried making the injected particles cause the temperature to be adjusted more naturally by turning off the thermostats when injection was occurring, and that seemed to work reasonably well, but it changes a lot of general behavior about the sim.  For instance, because the injected particles have a fixed injection speed, the overall temperature goes **down** in many cases when particles are injected.  This is a pretty big deviation from the way the Java version operates (the temperature remains constant during particle injection), so it seems a bit risky.  I discussed this with @arouinfar and @ariel-phet, and they agreed that the simple-but-special solution is preferred, at least for now.

**Comment by jbphet** [comment]
Assigning solely to @arouinfar to test and, if necessary, check in with Mike and Steve before deciding on whether this solution is acceptable.

**Comment by arouinfar** [comment]
Thanks @jbphet. Master looks good! I'll run it by Mike and/or Steve and let you know if there are any changes we should make.

**Comment by arouinfar** [comment]
Ran this by Mike, and he also thought it looked good. I'm going to leave this issue open, because it will need to be documented in the teacher tips.

**Comment by arouinfar** [comment]
Marking this as on-hold until it's time to write the teacher tips.

**Comment by arouinfar** [comment]
We're tracking the Teacher Tips in #168. Closing.
