### ISSUE TITLE
Pressure gauge behaviour at 0K

### ISSUE THREAD

**Issue by phet-steele** [phetsims/states-of-matter#154]
Currently, this is how sim pressure behaves at 0K:

HTML5:
- 0K and molecule/lid contact: Pressure very slowly settles on a value then remains constant
- 0K and no molecule/lid contact: Pressure remains constant

I talked with @arouinfar who said this behaviour was wrong. She suggested that in any scenario involving 0K, the pressure gauge should very quickly, yet smoothly, drop to 0.00 atm.

@jbphet this was observed on 1.0.0-dev.11 Mac Chrome, but is not necessarily for the testing task.

For comparison, here is how the Java behaves:

Java:
- 0K and molecule/lid contact: Pressure (relatively) quickly settles on a value then remains constant
- 0K and no molecule/lid contact: Pressure very slowly drops to 0

**Comment by jbphet** [comment]
The behavior of v1.0.0-dev.12 now matches the Java simulation in that pressure goes to zero when there is not contact with the lid.  I'm not sure that I agree that it should go to zero if there is contact with the lid, since where would be some repulsive force from the atoms on the lid, even in the absence of motion.  I'm assigning back to @arouinfar and @ariel-phet to decide if we're sure that we want pressure to be zero at absolute zero.  I can add special-case code to make this happen, but I want to be sure that this is the desired behavior before I implement it.

**Comment by arouinfar** [comment]
> I'm not sure that I agree that pressure should go to zero if there is contact with the lid, since where would be some repulsive force from the atoms on the lid, even in the absence of motion. 

Good point @jbphet. The behavior in dev.12 looks good!

Instead of closing, I'm going to leave this self-assigned and tagged for documentation in the Teacher Tips.

**Comment by arouinfar** [comment]
On second thought, we're tracking the Teacher Tips in #168. Closing.

**Comment by arouinfar** [comment]
After discussing with @ariel-phet @amyh-phet  and @jbphet and we've reversed this decision. The pressure should be zero at absolute zero because pressure is caused by momentum transfers between the atoms/molecules and the container. No motion = no momentum transfer = no pressure.

**Comment by phet-steele** [comment]
Works beautifully @jbphet.
