### ISSUE TITLE
Adding particles with few in the container slows down all active particles

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/states-of-matter#182]
When there are not many molecules in the container and more are added, all active particles will bleed velocity--often considerably, depending on how many particles are added and how many are already present. 

![bleeding velocity](https://cloud.githubusercontent.com/assets/22551096/20690619/eaf6a930-b588-11e6-8e1d-a862e7cb66e5.gif)

It is highly visible with oxygen but does occur with every atom/molecule to a lesser extent. I feel it could be highly related to https://github.com/phetsims/states-of-matter/issues/179, as in both it appears that one particle is leeching all the velocity/energy in the simulation. 

Related to https://github.com/phetsims/tasks/issues/725

Debug Info;
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.14/states-of-matter_en.html
Version: 1.0.0-dev.14 2016-11-09 20:12:59 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Language: en-US
Window: 1366x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"master"},"axon":{"sha":"8353fe86","branch":"master"},"babel":{"sha":"1294f048","branch":"master"},"brand":{"sha":"880a18de","branch":"master"},"chipper":{"sha":"957db829","branch":"master"},"dot":{"sha":"2765eb4d","branch":"master"},"joist":{"sha":"3bb749cf","branch":"master"},"kite":{"sha":"48cb255e","branch":"master"},"nitroglycerin":{"sha":"b19c167e","branch":"master"},"phet-core":{"sha":"4222a05a","branch":"master"},"phetcommon":{"sha":"8df1bf7d","branch":"master"},"query-string-machine":{"sha":"13ba45df","branch":"master"},"scenery":{"sha":"fb9d77c5","branch":"master"},"scenery-phet":{"sha":"89cce959","branch":"master"},"sherpa":{"sha":"7a7b88b0","branch":"master"},"states-of-matter":{"sha":"d9863972","branch":"master"},"sun":{"sha":"2f551060","branch":"master"},"tandem":{"sha":"005c5582","branch":"master"}}

**Comment by jbphet** [comment]
@ariel-phet - I demonstrated a variation of this issue to you a while back, and you said it wasn't a problem.  The thing I demonstrated was that injecting particles at low temperature could cause the injected particles to start off fast and then slow rapidly.  I believe you said something like, "That's fine - it just shows how cold it is in the container".  This issue that @EthanWJohnson just logged is essentially the same problem, but he noticed how it also affects the other particles in the container, which is more obvious when there are few particles.  This happens because the thermostat is trying to maintain the set temperature, which is quite low, so it slows all the particles down by quite a bit.

Does this need to be addressed, or is it acceptable as is?  The main way that I can think of to address it is to allow the temperature to go up when particles are injected, similar to what happens when the container is compressed.

**Comment by ariel-phet** [comment]
@jbphet you and I should discuss...though I understand (from your description) that the behavior shown is arising from the same fundamental model assumptions as the case you demonstrated for me, this case seems problematic.

The case you demonstrated was at very cold temperature, and things seemed to generally "jive" - particles looked like they were just coming out of the nozzle very cold. But here, adding particles and seeing energy removed from others without collisions seems a bit problematic.

It is a bit of an edge case since you need to get very few particles in the container to see the behavior, but we should talk a bit more before making a decision one way or the other.

**Comment by ariel-phet** [comment]
@jbphet the other thing I wonder is if the "rule" could just be that injected particles are injected at the temperature of the container, won't that make everything easy? So if things are cold, the particles are cold, if things are hot the particles are hot, if the come in with an average speed that matches the average kinetic energy, won't everything be hunky dory? The one exception would need to be at absolute zero, but I think you already have a rule for that (pumping in particles at absolute zero increase the temp above absolute zero)

**Comment by jbphet** [comment]
The problem with using slower velocities for injected particles at low temperatures is that particles end up overlapping at the injection point, which in turn creates a large amount of kinetic energy, which then has to be removed by the thermostat.  This would also look very unnatural, so I think we'd be robbing Peter to pay Paul.

@ariel-phet - if you think the current behavior is not acceptable, I think the best thing for me to try would be to allow the temperature to go up during injection.  This would be more physically accurate, and I **think** it would be reasonably easy to try.  If it opens a can of worms, I'll back it out and we can discuss further.

**Comment by ariel-phet** [comment]
@jbphet and I discussed over Skype, allowing temperature to increase as you pump particles in seems totally reasonable and worth investigation. We will try to implement in less than 5 hours, if things seem like they are spiraling into a big time sink we will revisit if we can live with this behavior.

**Comment by jbphet** [comment]
I've added the code that allows the temperature to change when particles are injected.  It appears to work well, and actually allowed me to remove some other special-case code that dealt with forcing the temperature to go up when particles are injected at absolute zero.  The change is available in http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.15/states-of-matter_en.html.

One question for @ariel-phet: This change causes the temperature to be recalculated based on the particle energies when an injection occurs.  In some cases, such as when the particles already in the container are quite hot, this can cause the temperature to go down.  I discussed this with @arouinfar and we decided to leave it, but you should test it out and make sure it seems reasonable.

**Comment by ariel-phet** [comment]
When I tested out several scenarios, all looked quite natural to me. I tested:
- very hot particles and pumping particles in
- absolute zero and pumping particles in
- very few oxygen molecules and pumping

**Comment by EthanWJohnson** [comment]
Looks good in all scenarios, as far as I can tell. There is still a slight decrease in velocity with low numbers of oxygen molecules, but it's practically invisible unless you're explicitly looking for it.
