### ISSUE TITLE
String for "Oxygen"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/states-of-matter#183]
From YY on unfuddle:

> In States of Matter, the string 'Oxygen' is used as a label for the molecule O2. In Atomic Interactions, the string 'Oxygen' is a label for the atom O.
> 
> These are different meanings, but happen to share the same word in English, which is why only one string is available for translation in the translation utility. This results in mistranslations in Atomic Interactions, since these two labels should be translated as distinct words in other languages (e.g. French, where the string should be "Dioxygène" in States of Matter, but "Oxygène" in Atomic Interactions.
> 
> Can an additional string be added for translation, as well as clear labels that indicate which is which within the utility (since just the word 'Oxygen' would be ambiguous)?

@jbphet I am not sure if this was ever addressed, would be good to do before publication. Perhaps there could be a string key that distiguishes "O2"

**Comment by jbphet** [comment]
It was addressed, and I just verified that there are two strings in the English file, one designated `oxygen` and the other designated `diatomicOxygen`.  Whether translators will figure this out and translate it correctly is another matter, since the key is the only hint that they will have on the current translation UI.  At any rate, the sim does support having a separate name for diatomic oxygen.  Closing.
