### ISSUE TITLE
Particle Blob Freezing when close to absolute zero, not heating

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/states-of-matter#186]
Seems to be related to https://github.com/phetsims/states-of-matter/issues/181, logging as asked.

When cooled to nearly absolute zero, but not quite, some blobs of particles will freeze at absolute zero long before others. While not an issue in of itself, this creates another issue where heating the container will not add any velocity to these already frozen blobs;

![near absolute zero freezing](https://cloud.githubusercontent.com/assets/22551096/20816754/103df2fc-b7e1-11e6-9c86-332d624d1f6c.gif)

This is even more of an edge case than https://github.com/phetsims/states-of-matter/issues/181, since it occurs very close to absolute zero, and mostly with small numbers of particles. 

Relevant Issue: https://github.com/phetsims/tasks/issues/746

Debug Info;
Name: ‪States of Matter‬
URL: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.15/states-of-matter_en.html
Version: 1.0.0-dev.15 2016-11-30 21:11:25 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Language: en-US
Window: 1366x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"47c12d19","branch":"master"},"axon":{"sha":"835a8b04","branch":"master"},"babel":{"sha":"538e7084","branch":"master"},"brand":{"sha":"6d85e08a","branch":"master"},"chipper":{"sha":"f57edeb4","branch":"master"},"dot":{"sha":"2765eb4d","branch":"master"},"joist":{"sha":"6430512a","branch":"master"},"kite":{"sha":"48cb255e","branch":"master"},"nitroglycerin":{"sha":"b19c167e","branch":"master"},"phet-core":{"sha":"9e9fe9de","branch":"master"},"phetcommon":{"sha":"16feff3e","branch":"master"},"query-string-machine":{"sha":"24ad72ef","branch":"master"},"scenery":{"sha":"1bf0a92e","branch":"master"},"scenery-phet":{"sha":"a3ccf91d","branch":"master"},"sherpa":{"sha":"c2e033b0","branch":"master"},"states-of-matter":{"sha":"87fba600","branch":"master"},"sun":{"sha":"0810acad","branch":"master"},"tandem":{"sha":"f37e6d7c","branch":"master"}}

**Comment by jbphet** [comment]
I tried several potential solutions to this, but all had unacceptable side effects on the operation of the sim.  The problem results from the same issue as #181, which is that the kinetic energy can end up very unevenly distributed at cold temperatures, and some particles end up with so little energy that they don't move visibly when the temperature starts to increase again and their kinetic energy is scaled up.  In order to solve #181, I added code to detect when the particles were heated up from absolute zero.  @EthanWJohnson has essentially found that if you get close to absolute zero, but not...quite...there, this code doesn't kick in and the uneven blob heating problem still exists.

I tried different thresholds, different min energies, and different strategies for deciding when to redistribute the energy in the particles.  They all had some undesirable side effect(s).

I propose that we don't address this.  As @EthanWJohnson says above, it's quite a corner case.  The user would first have to blow most of the particles out of the container, then cool it to almost, but not quite, absolute zero.  I can't image that this will happen very often, if ever, and when it does the results aren't particularly catastrophic. I tried cooling particles to 1K in the Java sim, and that has the problem where the particles increase in velocity over time, which seems worse to me.

Assigning to @ariel-phet for him to opine.

**Comment by ariel-phet** [comment]
@jbphet opine I shall.

@EthanWJohnson nice thorough find!

@jbphet I am going to agree with you here. We know how finicky this model can be and we are going to have to live with a couple of odd corner cases. What we are seeing, though a bit nonphysical, does show a change in KE of the moving particle, and I am guessing once it hits the blobs things start to even out.

Marking "won't fix" and closing.
