### ISSUE TITLE
User reported issue: temperature measurement during phase change

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/states-of-matter#190]
I absolutely love your simulations and use them in a great number of my lessons but I have a problem with the states of matter simulation – during a phase change the temperature continues to rise. This is wrong and contradicts what we need to teach our students.
 
Instead, I think the thermometer is measuring the total internal energy which is not the same as the temperature.

**Comment by arouinfar** [comment]
@oliver-phet phase changes/latent heat aren't addressed in SOM. See @ariel-phet's comment in the Teacher Tips issue https://github.com/phetsims/states-of-matter/issues/168#issuecomment-264054515.

@jbphet a user has suggested that the thermometer in SOM may be measuring the total internal energy, rather than the temperature. Is this true?

**Comment by jbphet** [comment]
The user is essentially correct, but there are so few particles that measuring temperature vs total internal energy just wouldn't work.  I'm not sure there is much we could do about this, at least not without a fair amount of thought and investigation.

I just discussed this with @ariel-phet and he's going to provide @oliver-phet with suggestions on how to respond to the user.

**Comment by arouinfar** [comment]
Thanks @jbphet!

**Comment by ariel-phet** [comment]
@oliver-phet please put the user in contact with me, and then close this issue.
