### ISSUE TITLE
Water rises in temperature excessively when molecules are pumped in

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/states-of-matter#208]
To reproduce:

1. On the phase changes screen, choose Water
2. Perform one full cycle of the the pump
3. The temperature rises dramatically (from 157 K up to ~300 or 400K)

The amount of temperature rise is quite inconsistent, which is suspicious as well. 

This behavior only occurs with water, but seems quite buggy. We should investigate once Gene Expression is moving to QA.

**Comment by jbphet** [comment]
I've spend a bunch of time on this hoping that there would be a reasonably quick and easy solution.  Alas, I' haven't found one yet, and need to move on to other things and come back to this later.

The basic issue is this: During normal operation of the main model, the target temperature of the substance (e.g. neon, water, etc.) is set by the user's actions, and the model works to keep the particle motions consistent with the temperature setting through the use of a couple of different "thermostats".  When a particle is injected, this relationship is briefly changed - the thermostats are turned off and the temperature that is calculated from the motion of the particles is used to set the target temperature.  The problem is that the temperature that is derived from the particle motion of the water is generally a bit higher than target temperature, so, in essence, when the thermostats are turned off, the temperature can go up fairly rapidly.

I've tried a couple of things to correct this.  The first one was to try to update the internal representation of the molecular structure of water such that the calculated temperature was closer to the set point.  This turned out to be pretty involved, and didn't change things at all that I could discern, so I bailed on that approach.  The second thing I tried was to make the main model calculate what the temperature increase **should** be when a new particle is injected and use that as the new set point instead.  This seemed to make a noticeable improvement to how water behaves, but had a detrimental effect on the other substances.  Mainly, they would exhibit odd behavior where they would appear to change temperature dramatically after injecting particles and then heating or cooling the substance.  I'd like to continue to pursue this avenue later, but need to drop it for now.

**Comment by jbphet** [comment]
I met with Paul Beale, who was one of the main designers of the particle model and has a lot of knowledge on statistical mechanics, and we brainstormed a few approaches.  In the end, the one that worked the best was to treat particle injection as a separate case from any other particle speed changes (such as interaction with the lid) and to calculate what the new temperature should be, and then use that as the set point.  I've implemented a dev version with this revised behavior and will solicit input from @ariel-phet and Paul Beale.  This version is available here: https://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.1.0-dev.1/states-of-matter_en.html.

**Comment by ariel-phet** [comment]
1.1.0-dev.1 seems to be working nicely with acceptable behavior. I think this version addresses the issue sufficiently.

**Comment by jbphet** [comment]
Paul also tested this out, and emailed me saying, "I agree. This appears much more physical. Thanks."

**Comment by jbphet** [comment]
@oliver-phet and @ariel-phet - I thought I recalled that a user had contacted us about this, but I don't see any record of it in this ticket.  My memory could be faulty, but I don't want to close this issue without closing the loop with the user(s) if they *did* report it.  Do you have any recollections or records on this?

**Comment by ariel-phet** [comment]
@jbphet yes this was user reported.

@oliver-phet looks like the original email was Aug 23 2017, subject "states of matter HTML5 version" to phethelp. I was in contact with the user, and will inform them of the change.

**Comment by ariel-phet** [comment]
Emailed the user. Self assigning to let them know the new version is published.

**Comment by ariel-phet** [comment]
I think this can be closed actually, the user did not respond about the dev version I sent with the new behavior. Closing.
