### ISSUE TITLE
User reported issue: shape of liquid

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/states-of-matter#212]
I'm writing to request a small change to the States of Matter Basics.    In this interactive, When you change from solid to liquid, the particles tend to stay bunched close together in a roughly defined shape, rather than settling at the bottom of the container (see the image below).  This is deceptive for beginning students.  I use this interactive in the opening chapter of my book, to convey the idea that macroscopic properties are a function of atomic/molecular structure.  Because of the prominence of this interactive, this bug is very problematic.

![image](https://user-images.githubusercontent.com/5090275/33576023-c6e00a18-d8fb-11e7-8d74-a0ca7269a26e.png)

I would like to propose two simple solutions to this problem:

1. In the initial solid state, position the atoms evenly across the bottom of the container, rather than a square shape.  While I understand the benefit of the square positioning for the solid (it conveys the idea of a definite shape), I think it's more important that that liquid not have a defined shape - and occupy the bottom of the container.
2. Alternatively, create a new starting position for the atoms when you click from from solid to liquid.  As it is now, if you are in solid and click "gas", the image changes immediately from the solid phase to gas phase description.  This works well.  Doing the same thing with the liquid (everything settled in the bottom of the container) would convey this idea much more smoothly than is happening now.

Thank you for considering these changes.  Please let me know if you have questions or concerns - I'm happy to set up a call to discuss this further if it would be helpful.  I look forward to working with you in the years ahead as we incorporate these excellent simulations into our digital books.

**Comment by oliver-phet** [comment]
@arouinfar Comments on this?

**Comment by arouinfar** [comment]
@oliver-phet I do not believe this is a bug, per se. Over time, a liquid does settle at the bottom of the container. 

<img src="https://user-images.githubusercontent.com/8419308/33613812-3533e4ea-d99b-11e7-8039-f70276111192.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/33613800-2d1cd258-d99b-11e7-9c40-7bb49ad32136.png" width=300>

Liquid takes the shape of its container due to gravity, but as we report in the teacher tips:
> Some amount of gravity is simulated, but it is minimal - just enough to keep the solid forms of the substances on the floor of the container. For this reason, substances in their liquid form don’t always spread out along the bottom of the container, like water does in a glass.

**Comment by jbphet** [comment]
I'm about to spend some time on another issue reported by a user (see #208), and we've already decided to also add support for Legends of Learning (see #211).  It's easy enough to try tweaking the amount of gravity.  @ariel-phet and @arouinfar - shall I do that at the same time?

**Comment by ariel-phet** [comment]
@jbphet - what about the user suggestion to have the initial liquid shape be more "settled" at the bottom of the container to begin with? Since when you click the gas phase it immediately spreads around the container, it seems reasonable to specify an approximate initial shape for the liquid.

It might also make sense to turn up the gravity a touch, but not too much (IMO). Right now the liquid also tends to show a bit of "vapor pressure" so we would not want the gravity so high that we did not see that effect.

**Comment by ariel-phet** [comment]
@oliver-phet please thank the user for the suggestion and let them know we are looking into this simulation currently for a few improvements and this seems like a reasonable suggestion.

**Comment by oliver-phet** [comment]
Email to user sent.

**Comment by jbphet** [comment]
Starting with a better initial position for the liquid state for all materials is definitely a possibility, but would be a bit more involved than simply turning up the gravity.  Right now, the code algorithmically positions the particles in a blob that, by itself, looks very unnatural, so the code then iterates the particle model a number of times without showing it to the user to get the initial positions.  A couple of possibilities to improve this would be:
1. Have a set of pre-determined positions for the particles.  I actually wanted to do this when the sim was originally developed, but didn't take the time due to other priorities.  This would be my preferred approach, but will take me at least a person-day to implement if things go well.
2. Try turning up the gravity during the initial non-visible iterations to get the particles to be lower and more spread out.  This *might* work, but tricky things like this tend to have unexpected consequence in this model, and I suspect I'd end up implementing some very tweaky code so that the particles don't end up bouncing off the bottom of the container (or some other odd behavior).

**Comment by jbphet** [comment]
Fixing this issue will also resolve somethting that Trish pointed out to me a while ago, but we never logged.  If the user pauses the sim while the substance is in the gas or solid state, and then changes to the liquid state, the initial, semi-organized particle arrangement can be seen.  Here is a screen shot to illustrate:

![image](https://user-images.githubusercontent.com/3082831/35362186-f0a25120-0129-11e8-949c-e56907412a48.png)

**Comment by ariel-phet** [comment]
This should get the new `status:addressed-waiting-deploy` label. Self assigning to add that when availabe

**Comment by KatieWoe** [comment]
Looks good.  Closing

**Comment by jbphet** [comment]
@oliver-phet - please tell the individual who requested this that we have improved the behavior of the sim when setting liquid states.

**Comment by oliver-phet** [comment]
User emailed. Closing.

**Comment by KatieWoe** [comment]
Looks good on basics 1.1.0-rc.2

**Comment by oliver-phet** [comment]
Another user just wrote in about this behavior:

> I have used PhET’s and appreciate access to them.  I do have one problem with a simulation and think it may be a programming error.   It may be that I am missing something.
> In the “STATES OF MATTER: BASICS” , within the “STATES” activity, please select Oxygen.   When you select LIQUID , the oxygen remains clumped in a pile in the middle of the cylinder.   I would like to use Oxygen with my 8th graders because they can identify that it is typically in its gaseous phase at room temp.  When I have them view the liquid, this view is confusing and so I have used Argon instead.
> Is there something I am missing?

Here's what liquid Oxygen looks like after a minute or two:

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/5090275/73392358-e6a01580-4296-11ea-9ee3-6f8d20661497.png">

**Comment by jbphet** [comment]
The attraction between O2 molecules is particularly high when compared to that of the noble gasses, which causes the sim to form a clump in this case, much like a droplet of water forms on a smooth surface due rather than the water spreading evenly into a thin layer.  I know that this tends to cause confusion, and I may be able to change things so that oxygen behaves more like the other substances at liquid temperatures, but it wouldn't be trivial.

@arouinfar and @oliver-phet - back to you to decide whether this is a reasonable answer or whether we should pursue it further.  Feel free to bring in @ariel-phet if you are so inclined.

**Comment by arouinfar** [comment]
Liquid oxygen is noticeably different than the other liquids. While I think it certainly would be nice to fine tune its shape a bit further, I can't speak to the priority of such a change (especially a non-trivial one). If we want to make this change, realistically it makes sense for @jbphet to work on it while he's already in the sim, but that probably doesn't mesh well with PhET-iO delivery goals. I'll defer to @kathy-phet and @ariel-phet.

**Comment by ariel-phet** [comment]
I fundamentally disagree with this user's assessment - Oxygen looks significantly different in the solid, liquid, and gas phases. I think the user is perhaps making the assumption that in the liquid state the oxygen should "puddle" in the bottom of the container. But really the learning goal here is between the ordered crystaline state (solid), the liquid phase, and the gas phase, which are really about interaction distance and correlation between movement and such. 

I don't think any changes should be made.

@arouinfar perhaps it would be useful to mentioning something in the teacher tips, but I don't think any changes are warranted (especially considering the popularity of the simulation and this comment being the only known issue from a user).

**Comment by arouinfar** [comment]
Thanks @ariel-phet. You make a very good point. The teacher tips already had some information regarding the shape of the liquid, but I added to it a bit. 

Updated teacher tips have been uploaded, closing.

**Comment by oliver-phet** [comment]
@ariel-phet @arouinfar User replied back:

> Please forgive if this seems pushy, but I wanted to restate a concern.  Due to Coronavirus, I have been working on next years prep.  I was focusing on demonstration of the relationship between temperature and kinetic energy at a very basic level for helping middle schoolers visualize this. 
> I went back to look at this Gizmo and I really think its overall effectiveness, even at the high school level is hampered by the logic of this being a low gravity environment.   Water in its liquid form as a ball inside of a container is foreign to every day experience.    This is also not clarified in the pHET simulation screen.

**Comment by arouinfar** [comment]
@ariel-phet can you take over communication with this user?

Gas Properties or Gases Intro may better suit their goal of connecting temperature and kinetic energy.

**Comment by ariel-phet** [comment]
Sure @arouinfar 

@oliver-phet can you forward the relevant email to me.

**Comment by oliver-phet** [comment]
Forwarded!

**Comment by ariel-phet** [comment]
Ok, I will take it from here. Closing.
