### ISSUE TITLE
User feedback, multiple

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/states-of-matter#214]
@arouinfar We are working with a publisher that is going to embed states of matter, and the author had this feedback. Let me know if you would like these broken into separate issues.

Feedback on details the author found not correct: 
- Festkörper (solid body): the start as cube is good with neon, argon and oxygen. With Water, the cube is not really recognisable because the isolated watermolecules are too far from each other. 
- Festkörper: the author is puzzled because the cubes of neon, argon and oxygene wander as solid cubes from left to right shortly before melting point. 
- Festkörper: the author thinks it is not correct that with (solid) water one sees a movement of wandering. With (solid) forms, one should only see a movement of trembling. 
- Flüssigkeit (fluidity/liquidity): the start in the shape of a drop puzzles him. This only would happen during zero gravity. He would recommend particles of water on the bottom at the start (instead of a drop). 
- the author thinks that the indication of temperature of melting point/boiling point are not correct. Correct would be: 
Neon - 249 °C / -246 °C 
Argon -189 °C / -186 °C 
Oxygene -218 °C / -183 °C 
Water 0 °C / 100 °C 
- phase diagram: the red point does not move correctly. 
- the author would prefer not atm as indication but mbar or bar. 

(Note: "Festkörper" is German for solid, "Flüssigkeit" means liquid.)

**Comment by ariel-phet** [comment]
@jbphet I have to say the wandering does not really bother me, but I suppose it is a bit odd in the way we normally think of a solid.

I am wary about making a change since this model tends to be tweaky, but if you think it is 3'ish hours, that at least seems reasonable to explore. I would say we do that exploration in a way that is easy to revert and test the consequences. Does fixing the wandering issue:
1. Cause other strange behavior/bugs?
2.  Hit performance at all?

As long as the answers to 1 & 2 are no, seems reasonable to move forward.

**Comment by jbphet** [comment]
The wandering is probably related to this issue: https://github.com/phetsims/states-of-matter-basics/issues/15.

**Comment by jbphet** [comment]
Here are a some screenshots of the "wandering" behavior.  My test procedure was to start the sim, select the first screen, and apply heat for 4 to 5 seconds.  Not all cases look like these, but a significant proportion do, and it is definitely a bit unphysical since the particles shouldn't collectively gain energy in a single direction.

![image](https://user-images.githubusercontent.com/3082831/43488434-ff16b5d4-94d6-11e8-991a-8ea65f7d90d1.png)

![image](https://user-images.githubusercontent.com/3082831/43488619-908e7b6e-94d7-11e8-83fd-69fff8de2a2f.png)

![image](https://user-images.githubusercontent.com/3082831/43488575-6d7ce26e-94d7-11e8-8e52-ae5b60ec747d.png)

![image](https://user-images.githubusercontent.com/3082831/43488684-c3276f2c-94d7-11e8-815f-005f52a8e894.png)

**Comment by jbphet** [comment]
In the course of working on the drift issue I added some debug code that shows the accumulation of added velocity.  This turned out to be very helpful in numerically understanding the cause of the drift, so I published a dev version that included this debug output.  The version is https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-dev.2/phet/states-of-matter_en_phet.html and the output can be seen on the console when heating or cooling a single-atom substance, i.e. neon or argon.

**Comment by jbphet** [comment]
In the 8/2/2018 design meeting we decided to double check the temperature values after the latest mods to the thermostats are complete.  If they are reasonably accurate, we won't change them.

**Comment by jbphet** [comment]
Also in the 8/2/2018 design meeting, we reviewed the drift compensation.  I demonstrated the sim with compensation in the horizontal direction only and with compensation in by the horizontal and vertical directions, and we decided to go with horizontal only.  Our reasoning is that the rising up of the substance looks reasonably good, and is what users are used to.  Also, this behaved somewhat oddly when showing it over zoom, possibly because of large dt (delta time values) in the sim.

**Comment by jbphet** [comment]
@arouinfar - in comment https://github.com/phetsims/states-of-matter/issues/214#issue-311303288 above, the person who is interested in integrating the sim into their learning environment had some input on what he/she saw as the melting and boiling points of the substances.  I've just published a new dev version (link below) - can you check and see if you think the temperatures need any adjustment?  It's actually fairly easy to change the temperature values shown on the thermometer for a given substance because it is just a mapping from the values in the normalized particle model.

https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-dev.3/phet/states-of-matter_en_phet.html

**Comment by arouinfar** [comment]
@jbphet neon and argon are looking great! 

I've noticed that liquid oxygen doesn't spread along the bottom of the container, like the other liquids. I started from a solid, and then gradually heated up the sample. I find that 1.1.0-dev.3 generally behaves about the same as the published version.

Solid > Liquid Water behaves pretty well, but the Liquid > Gas transition is poorer in 1.1.0-dev.3 than in the published version.

For the screenshots in this table, I started from the solid state, and slowly increased temperature. I also allowed for some time for the sample to settle/equilibrate before taking the screenshots.

| Temp (*C) | State  |  Comments about 1.1.0-dev.3  | 1.1.0-dev.3 |  Published |
|---|---|---|---|---|
| -218  | Melting Point  |  Looks pretty solid | <img src="https://user-images.githubusercontent.com/8419308/43912684-336e5ab8-9bc0-11e8-86e1-f122890dd0c0.png">  | <img src="https://user-images.githubusercontent.com/8419308/43913168-8bca045e-9bc1-11e8-8886-12ef9c923bf6.png">  |
| -202  | Liquid  | Moves more like a liquid, but still a big blob  |  <img src="https://user-images.githubusercontent.com/8419308/43912719-49e78e4a-9bc0-11e8-84fd-c109f1f3c230.png">  |  <img src="https://user-images.githubusercontent.com/8419308/43913250-d1cb2b18-9bc1-11e8-90dc-95eec9d0ec7d.png"> |
| -191  | Liquid  | Doesn't conform to container, but does look like the liquid button |  <img src="https://user-images.githubusercontent.com/8419308/43912753-665fc380-9bc0-11e8-947c-64d235ecc053.png"> | <img src="https://user-images.githubusercontent.com/8419308/43913375-0814efd8-9bc2-11e8-8473-a6f6961fd38a.png">  |
| -178  | Gas  | Looks like floating solidish/liquidish blob  | <img src="https://user-images.githubusercontent.com/8419308/43912949-f5a83c34-9bc0-11e8-9077-907ab76788dd.png">  | <img src="https://user-images.githubusercontent.com/8419308/43913408-1d180a28-9bc2-11e8-8ee5-3ea02504000c.png">  |
| 100  | Boiling Point  | Does not appear to be boiling  | <img width="446" alt="screen shot 2018-08-09 at 12 04 36 pm" src="https://user-images.githubusercontent.com/8419308/43917224-ee5258dc-9bcc-11e8-8f38-d2eb2802f2f6.png">| <img width="448" alt="screen shot 2018-08-09 at 12 16 01 pm" src="https://user-images.githubusercontent.com/8419308/43917791-756c9c64-9bce-11e8-9463-3cdbe3560680.png"> |
| 120  | Gas  | Looks like liquid  | <img width="451" alt="screen shot 2018-08-09 at 12 05 02 pm" src="https://user-images.githubusercontent.com/8419308/43917261-106a09b0-9bcd-11e8-8481-1b2820289370.png">  | <img width="452" alt="screen shot 2018-08-09 at 12 16 13 pm" src="https://user-images.githubusercontent.com/8419308/43917755-5e23da0e-9bce-11e8-9fa8-6c1acd52c1c8.png"> |
| 219  | Gas  | Still looks like liquid  | <img width="454" alt="screen shot 2018-08-09 at 12 05 33 pm" src="https://user-images.githubusercontent.com/8419308/43917360-59dcebee-9bcd-11e8-99af-e331463842ae.png">  |<img width="443" alt="screen shot 2018-08-09 at 12 16 31 pm" src="https://user-images.githubusercontent.com/8419308/43917726-4b06564a-9bce-11e8-8a29-8071b87ad7a5.png">   |
| 438  | Gas  | Finally starts to look like a gas  | <img width="447" alt="screen shot 2018-08-09 at 12 06 06 pm" src="https://user-images.githubusercontent.com/8419308/43917490-b6efa592-9bcd-11e8-9438-dd25c947ef62.png">  | <img width="461" alt="screen shot 2018-08-09 at 12 16 58 pm" src="https://user-images.githubusercontent.com/8419308/43917682-324f7942-9bce-11e8-8e53-1edda180259f.png">  |

**Comment by KatieWoe** [comment]
Found the same thing as @arouinfar Linking to phetsims/QA/issues/164

**Comment by jbphet** [comment]
I've remapped the temperature behavior for oxygen and water, and @arouinfar and I reviewed it from master and she said that it seemed much improved.

**Comment by KatieWoe** [comment]
For https://github.com/phetsims/QA/issues/185 it looks like some of the melting and boiling points are off by a few degrees (boiling point of neon for example) but it does look much better.  Behavior of water when boiling looks a bit off as well.  But I agree with @arouinfar that it is much better than it was.

**Comment by KatieWoe** [comment]
Also for https://github.com/phetsims/QA/issues/185.  I believe this is what was meant by "the red point does not move correctly."  Changing temperature and pressure only moves the dot along the phase change line between solid and gas, and later liquid and gas, until it reaches the supercritical fluid section.  It never is in the solid, the liquid, or the gas section, only on that line.
https://drive.google.com/file/d/1IXq28n4mZVjspsmMs9kfoxcRLltW0uLM/view?usp=sharing

**Comment by KatieWoe** [comment]
@jbphet Do you want this issue closed?

**Comment by jbphet** [comment]
I spoke with Paul a couple of times in person about this, and sent him a link, but he never got back to me.  He said that it's probably not a big deal in any case, and that if I didn't hear back in time we shouldn't worry about it.  So, with that in mind, I'm going to close this issue and move forward with the deployment.

**Comment by jbphet** [comment]
@oliver-phet - could you let the person who made the requests that prompted this issue that most, if not all, of their comments have been addressed in the new v1.1.0 version.

**Comment by oliver-phet** [comment]
This is from the same user that requested default Celsius. Email sent. Closing.

**Comment by KatieWoe** [comment]
I've noticed that water starts melting (r registering as a liquid) at about -27 C.  @jbphet @arouinfar is this acceptable?

**Comment by KatieWoe** [comment]
Other than that, looks fine on basics 1.1.0-rc.2

**Comment by arouinfar** [comment]
>(r registering as a liquid) 

I'm not sure I follow @KatieWoe.  When I melt solid water, the density of the water most notably increases near 0 C (+/- a few degrees) and the vibrations of the molecules really pick up. 

I think the behavior looks correct in rc.2, so I'll leave this closed.
