### ISSUE TITLE
Thermometer resets tilted on states screen.

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/states-of-matter#223]
**Device:**
Mac OS X El Capitan v. 10.11.6
**Browser:**
Chrome v. 68.0.3440.106
**Problem description:**
Noticed while testing https://github.com/phetsims/QA/issues/164 on the states screen heat an atom or molecule to the point where the lid flies off (I used Argon) and choose a different atom or molecule to reset the lid. The thermometer should now be reset to its original position but it will be cocked to the side. The thermometer and sim still function as expected, this is more of a design note. I have attached a screenshot of how the thermometer looks in this tilted position.
![screen shot 2018-08-15 at 8 59 12 am](https://user-images.githubusercontent.com/30352536/44157059-b64ac400-a06e-11e8-9fa5-da4ffb25c4a2.png)

**Comment by KatieWoe** [comment]
Just tested this on the published sim and it does occur there as well.

**Comment by jbphet** [comment]
Interesting test case, I've never done that.  I've added code to reset the rotational angle of the thermometer when the lid is returned after the container explodes.

**Comment by JRomero0613** [comment]
I've just tested this issue in master on macOS Sierra v. 10.12.6 on Chrome v. 68.0.3440.106, Firefox v. 61.0.2, and Safari v. 10.1.2.12603.3.8 and it has been fixed. I move to close this issue, with a check to make sure it has been fixed in the next round of testing.

**Comment by phet-steele** [comment]
I've caused this in 1.1.0-rc.1. The rotation is correct, but the position is not.

![image](https://user-images.githubusercontent.com/5863899/45451578-adaed300-b698-11e8-9b7f-f4b21f82cafd.png)

I'm not sure how close to the original steps I was (since I think they may have been missing some details), nor am I sure that what I did is important, but here they are:

1. Heat Argon.
2. JUST as the lid blows, BEFORE the thermometer leaves the top of the screen, click Neon.

Seen on Win 10 Chrome. For phetsims/QA/issues/185.

<details>
<summary>Troubleshooting Information</summary>

![image](https://user-images.githubusercontent.com/5863899/45451674-f8304f80-b698-11e8-967a-e6f4dcc54561.png)

</details>

**Comment by KatieWoe** [comment]
Using @JRomero0613 method it does seem fixed (this is the same as @phet-steele method but clicking Neon later, after the lid leaves.)
@phet-steele that's a good catch.  One addition to step 2.  It looks like you need to click Neon before the lid leaves the screen, not necessarily before the thermometer, leaving a bit more wiggle room.  Most easily done if you have a multitouch screen.
![new version](https://user-images.githubusercontent.com/41024075/45455389-25cec600-b6a4-11e8-859c-269edd993740.PNG)

**Comment by KatieWoe** [comment]
Hitting the orange reset button does not move the thermometer back.

**Comment by jbphet** [comment]
I certainly appreciate how thoroughly you folks test these things!  It turns out that if the thermometer node is moved back into place when rotated (due to its movement after an explosion), and then de-rotated to a rotation angle of 0, its position is off because the rotation operation uses the origin of the node rather than its center.  I fixed this be changing the order of operations to do the de-rotation first, then set the position.

**Comment by jbphet** [comment]
Assigning to QA to updated based on the results of the 1.1.0-rc.2 testing.

**Comment by KatieWoe** [comment]
Confirm 1.1.0-rc.2

**Comment by jbphet** [comment]
Deployed in v1.1.0, closing.
