### ISSUE TITLE
Overlapping Pointer Areas

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#226]
**Test device:**
Dell Laptop
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/185
There are two instances where pointer areas overlap, or could potentially interfere with usage.  Unsure if this is fixable in one instance, and it doesn't seem like it interferes much, so posing as a question.  This is also in the published version.  The first instance is on the Phase Changes screen.  The finger's red pointer area overlaps with the drop down box that selects temperature units.  The second is found on the Interaction screen in the graph with adjustable attraction.
**Steps to reproduce:**
1.Use the quarry parameter showPointerAreas
2. On the Phase Changes screen, note that you can both move the finger and manipulate the temperature drop down at the same time.
3. On the Interaction screen select adjustable attraction.
4. Note that the moveable atom on the graph and the adjustable minimum potential energy overlap in pointer areas.  This may cause some difficulty in manipulation, but playing with it didn't reveal many difficulties.

**Screenshots:**
![point2](https://user-images.githubusercontent.com/41024075/45499235-38470f00-b739-11e8-8cb7-94d9ec7cddb1.PNG)
![overlap](https://user-images.githubusercontent.com/41024075/45499239-3c732c80-b739-11e8-9396-541bc8433d57.PNG)

**Troubleshooting information (do not edit):**

<details>

Name: ‪States of Matter‬
URL: https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.1/phet/states-of-matter_en_phet.html?showPointerAreas
Version: 1.1.0-rc.1 2018-09-12 18:56:30 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
Language: en-US
Window: 1536x732
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"d7ba44e2","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bbbb514a","branch":"HEAD"},"dot":{"sha":"820111c8","branch":"HEAD"},"joist":{"sha":"fb860843","branch":"HEAD"},"kite":{"sha":"59755f7e","branch":"HEAD"},"nitroglycerin":{"sha":"ccaab9cd","branch":"HEAD"},"phet-core":{"sha":"68a89cc4","branch":"HEAD"},"phet-io":{"sha":"364077cf","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"abc4ae3e","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"429886e7","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ef0b0b0c","branch":"HEAD"},"phet-io-wrappers":{"sha":"7ec1a04a","branch":"HEAD"},"phetcommon":{"sha":"22b158d0","branch":"HEAD"},"query-string-machine":{"sha":"c2e502fb","branch":"HEAD"},"scenery":{"sha":"415371c3","branch":"HEAD"},"scenery-phet":{"sha":"94b92879","branch":"HEAD"},"sherpa":{"sha":"a9fd066b","branch":"HEAD"},"states-of-matter":{"sha":"de26f688","branch":"HEAD"},"sun":{"sha":"3086e97a","branch":"HEAD"},"tambo":{"sha":"0e5b9133","branch":"HEAD"},"tandem":{"sha":"a2348c0c","branch":"HEAD"}}

</details>

**Comment by jbphet** [comment]
@KatieWoe - does this issue exist on the published sim?

**Comment by KatieWoe** [comment]
@jbphet Yes.  Mentioned in problem description.

**Comment by jbphet** [comment]
The first issue noted - the one where the touch area for the finger overlaps the thermometer - doesn't seem to present an issue with respect to interaction with either the finger or the thermometer.  The thermometer is on top of the finger in the z-order, so the user can easily manipulate it.  I played around with this on a touch-based device and I don't think it is likely to cause any problems for users.

The second issue noted is definitely tricky because of the number of things sitting at the bottom of the curve.  However, I think users will figure out pretty quickly that the little ball has preference (i.e. is at the top of the z-order) and can move it out of the way if they want to interact with the curve shape.  Since both the line and the up/down arrow are for setting the curve depth, it doesn't matter which one of these the user selects, since the effect is the same, so there isn't a concern for that aspect.  There isn't much else we can do here that I can think of.  

Given what I've said here, and that this is how the published version works and we've never received any complaints, my recommendation would be to leave these as they are.

Assigning to @ariel-phet to make sure he concurs, and he can close the issue if so.

**Comment by ariel-phet** [comment]
@jbphet @KatieWoe considering the popularity of the published simulation, lack of complaints, and no obvious improvements that could be made, I think we will leave as is.

However, @KatieWoe definitely keep pointing out issues like this, the attention to detail is greatly appreciated!
