### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#243]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* When pause/play button is play, the pointer areas overlap a bit.  (I believe this has already been solved)
* I found it quite difficult to switch between Kelvin and Celsius
The +/- zoom buttons on the last screen could sometimes be a bit difficult 

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56227422-ab4b9780-6032-11e9-840d-87c8edb69810.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56227423-ab4b9780-6032-11e9-83f8-f58d226fcab3.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56227425-ab4b9780-6032-11e9-8903-8a7d40f47a57.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56227427-abe42e00-6032-11e9-85e9-ef3c5acd86c7.png)

**Comment by KatieWoe** [comment]
Also, should the pump have touchSnag?

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

> When pause/play button is play, the pointer areas overlap a bit. (I believe this has already been solved)

This does not appear to be an issue in master. 

> I found it quite difficult to switch between Kelvin and Celsius

We may be somewhat constrained by the bounds of the ComboBox. @jbphet can you look into this? 
I tested on my phone, and didn't have any difficulty, so I would be fine with leaving as-is, if necessary.

> The +/- zoom buttons on the last screen could sometimes be a bit difficult

`RectangularButtonView` does not support asymmetric pointer area dilation, but it is being considered in https://github.com/phetsims/sun/issues/500. An alternative option would be to move the zoom out button down a bit to allow for larger pointer area dilation. I'll defer to @jbphet.

Here's a mockup of an asymmetric dilation.
![image](https://user-images.githubusercontent.com/8419308/56305258-2c6f6100-60fd-11e9-974f-adca92addea1.png)




> Also, should the pump have touchSnag?
> Should touchSnag be on the atoms? [suggested in https://github.com/phetsims/atomic-interactions/issues/78]

If `touchSnag` is something that can be quickly added, then I'd be in favor. Otherwise, the touch areas seem generous enough as-is, so I'll leave it up to @jbphet.

**Comment by SaurabhTotey** [comment]
I haven't changed the kelvin-celsius conversion ComboBox. I have, however, given the zoom buttons on the last screen an asymmetric dilation that looks like the below image in master.
<img width="74" alt="ZoomButtons" src="https://user-images.githubusercontent.com/22577113/60468857-22e39880-9c18-11e9-8489-cb5322208b0e.png">
Also, the particles in the last screen (the large draggable one at the bottom and the marker on the graph) now have touch snag. I believe the bike pump has touch snag by default; when I tested it, it seemed to have touch snag.

**Comment by arouinfar** [comment]
Looks good @SaurabhTotey, thanks!

**Comment by KatieWoe** [comment]
Relevent changes seem to be made in https://github.com/phetsims/QA/issues/525, though buttons in https://github.com/phetsims/states-of-matter/issues/243#issuecomment-507440065 have been removed. Closing for now. Will reopen if problems show up.
