### ISSUE TITLE
use SCENERY_PHET/TimeControlNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#250]
Noticed while working on phetsims/scenery-phet#575.

SOM currently has its own implementation that is similar to SCENERY_PHET/TimeControlNode, embedded in AtomicInteractionsScreenView (lines 172-216).  A couple of things that are surprising:

(1) This sim is being (has been?) instrumented for PhET-iO.   Did no one do a review to identify where common components should be used?   Instrumentation of this custom implementation was both undesirable and unnecessary.

(2) This big chunk of code is in AtomicInteractionsScreenView, rather than being encapsulated in its own class.  

In any case, SOM should be using common code SCENERY_PHET/TimeControlNode. One notable difference is that bending-light uses "Slow Motion", where common code uses "Slow". Another difference is the position of the radio buttons.

This is important for phet-io and a11y.

**Comment by kathy-phet** [comment]
@jbphet - Agreed this should be updated to use the common code component, as we have been honing the PhET-iO structure and instrumentation of that element.

**Comment by jbphet** [comment]
The `TimeControlNode` has been integrated into the sim.  This has caused some changes to the look and behavior versus the previous versions of the sim.  The two most significant are:

+ The play/pause button no longer inflates when in pause mode
+ On the Atomic Interactions screen, the play/pause/step buttons are on the other side of the slow motion radio buttons, and the wording is slightly different

@arouinfar - please review and make sure that you're okay with these changes.  There is not much we can do about it if not, other than to revert back to the custom version (which I don't think we want to do due to phet-io consistency), but I thought you should review anyway.

**Comment by chrisklus** [comment]
@jbphet It looks like SOMPlayPauseStepControl.js was already extending TimeControlNode and just added sim-specific options. So the option from line 31: `scaleFactorWhenPaused: PAUSE_SIZE_INCREASE_FACTOR` should still work just fine for inflating the pause button (when nested into `playPauseOptions` like it was).

**Comment by jbphet** [comment]
Great suggestion @chrisklus - I've made that change.

@arouinfar - now the only change is the normal-versus-slow-motion selection interface on the Atomic Interactions screen.

**Comment by arouinfar** [comment]
> The play/pause button no longer inflates when in pause mode

For the record, I would have been fine with losing this behavior. It's something we've done in older HTML5 sims, and in most cases I don't think it's necessary. That said, I'm fine with keeping the behavior as-is, so thanks to @chrisklus for pointing out the necessary option.

> On the Atomic Interactions screen, the play/pause/step buttons are on the other side of the slow motion radio buttons, and the wording is slightly different

I prefer the look that's now in master, and the wording change is something we decided on in the design of `TimeControlNode`. I thought that `TimeControlNode` was going to support having the radio group on either side of the buttons, but in this case I do prefer the radio buttons on the right.

Since I don't think there's anything else left for this issue, I'll go ahead and close.

**Comment by jbphet** [comment]
@arouinfar and I discussed the button expansion in person and decided to remove it.
