### ISSUE TITLE
Phet-io won't load

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#260]
When trying to open studio on master:
![statesproblem](https://user-images.githubusercontent.com/41024075/75897823-69684300-5df6-11ea-8c3c-c858498c522b.png)

**Comment by pixelzoom** [comment]
Looks to me like the Property being passed to the RadioButtonGroup has not been instrumented.

**Comment by jbphet** [comment]
Close.  It was that I was using `tandem` instead of `tandemName` for the radio button items, and wasn't passing in a tandem to `AquaRadioButtonGroup`.  I've fixed this.

Also, I talked with @KatieWoe, and she isn't going to log any more issues related to validation of tandems for now, since getting all tandems to validate is under the umbrella of instrumenting for phet-io, and there is already an issue for that.  Closing.
