### ISSUE TITLE
Pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter#271]
Related to #265 and #266 

Phase Changes Screen, Interaction Strength slider:
- [x] Change color of slider thumb to match the purple used on the Interactions screen.
- [x] Reduce size of "weak" and "strong" tick mark labels to match the size used on the Interactions screen.

Interactions Screen, TimeControlNode:
- [x] Move the Normal/Slow radio button group to the right side of the button group.

**Comment by jbphet** [comment]
Changes made.  @arouinfar - please review on master.  I ended up moving the `TimeControlNode` on the "Interaction" screen a little to the left so that the radio buttons didn't end up too close to those in the "Forces" panel when "Adjustable Attraction" is selected.  Please check it out and see if you think it - are any of the other changes - need any further revision.

**Comment by arouinfar** [comment]
Looks good in master. Thanks @jbphet!
