### ISSUE TITLE
In PhET-iO states screen, top iframe jumps when bottom iframe updates

### ISSUE THREAD

**Issue by muedli** [phetsims/states-of-matter#279]
<b>Test Device</b>

Liam's MacBook Air

<b>Operating System</b>

macOS 10.15.4

<b>Browser</b>

Google Chrome 81.0.4044.138

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/501. I know we expect the states wrapper to be a bit laggy, but it seems like the lagginess is extending to the top iframe. Every time the bottom iframe updates, the top iframe does a "jump." Probably a non-issue issue, and if so, feel free to close. QA just likes to err on the side of caution.

<b>Visuals</b>

![issue](https://user-images.githubusercontent.com/60749003/82248065-c6a76700-9904-11ea-9b01-d40e92882fbe.gif)

**Comment by jbphet** [comment]
@zepumph and @samreid - this behavior is almost certainly lag due to the time it takes for the state to be extracted from the top sim and sent over the PhET-iO API.  I don't have any sense of whether or not this is a legitimate cause for concern, since I don't know whether we intend our customers to use it in this way or whether this is more of a "stress test" situation.  I suspect it is the latter.  Is this something I should spend time optimizing?

**Comment by samreid** [comment]
This visual hiccup is to be expected and should not be optimized.  PhET-iO state is not used at the moment for time-dependent playback, the mirror inputs wrapper would be used for that.

**Comment by jbphet** [comment]
Thanks @samreid.  Closing.
