### ISSUE TITLE
Studio non-neon movable atoms have non-zero velocity when still

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#282]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome 81.0.4044.138
**Problem description**
For https://github.com/phetsims/QA/issues/501
When looking at the velocity property for the movable atom on the interaction screen, it will be non-zero for an atom that hasn't been touched if it is non-neon.

**Visuals**
![changingvelocityofstillatom](https://user-images.githubusercontent.com/41024075/82258801-bb116b80-9917-11ea-8ed4-e54f78d6d1ab.gif)

**Comment by loganbraywork** [comment]
In Firefox, movable atom velocity in studio is constantly changing for all atoms on startup, including neon. 
![2020-05-18StatesPhetIOVelocity](https://user-images.githubusercontent.com/54685448/82262959-2448ad00-991f-11ea-9e66-e52817362f82.gif)

**Comment by jbphet** [comment]
This is due to floating point error.  The position of the bottom of the potential well can't be perfectly calculated, so there ends up being some minimal forces that cause small motion in some cases.  I've added code to detect when the atom is at zero velocity near the center of the well and experiencing minimal forces, and at that point reduce the forces to zero.  It seems to work so far.

@KatieWoe - please have QA test this on master for both states-of-matter and atomic-interactions and, if all looks good, unassign it but leave it open.  This would be a good one to verify in the next release cycle.

**Comment by KatieWoe** [comment]
Looks fixed

**Comment by KatieWoe** [comment]
Looks good in https://github.com/phetsims/QA/issues/525. Will reopen if something comes up
