### ISSUE TITLE
Green arrows for dragging the hand don't show up in state

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#284]
For https://github.com/phetsims/QA/issues/501. Found in Win 10 Chrome.
In the states wrapper, when the green arrows show up to indicate that the lid can dragged, those arrows do not show up in the bottom state sim.
![shouldgreenarrowshowup](https://user-images.githubusercontent.com/41024075/82266747-c8ceed00-9927-11ea-9414-a629e744b30d.gif)

**Comment by jbphet** [comment]
This behavior seems expected to me.  The hand is just a view element, it has no existence in the model, so we shouldn't expect things like movement hints to show up.

@zepumph - since you're the phet-io point man on this, can you confirm?  If so, please close.  If not...well, I don't even want to go there.

**Comment by zepumph** [comment]
Yes agreed. Hover behavior has traditionally not been included in state. Over to QA to update documentation if desired.

**Comment by KatieWoe** [comment]
Ok. In that case closing.
