### ISSUE TITLE
Possible to have overlapping dropdown boxes in Studio

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#291]
For https://github.com/phetsims/QA/issues/501. Found on ChromeOS. Happens on other platforms too.
In studio, removing elements in the dropdown/tool boxes changes their size. It is possible to create a scenario where the boxes overlap due to this fact.
Steps:
1. Go to the interaction screen. Stay on neon for now
2. Make the diameter slider invisible
3. In the sim, change to adjustable attraction atoms and observe size of boxes
4. While in this state, make the diameter slider visible again

![overlappingboxes](https://user-images.githubusercontent.com/41024075/82493217-d362c100-9aa4-11ea-9f71-a18b03f6a923.gif)

**Comment by KatieWoe** [comment]
Note that this does resolve in this instance if you switch out of, and then back into, adjustable attraction atoms.

**Comment by jbphet** [comment]
@arouinfar and @kathy-phet - Do we really need to handle situations like this?  I can certainly do it, but there are probably an awful lot of cases where the user can do arbitrary things through studio that will mess up the layout, and it will be quite time consuming to address them all.

If I should address, please assign back to me, otherwise close.

**Comment by kathy-phet** [comment]
I believe we saw this bug when we were in Studio. It is not persistent in any published sim, so we did not report it. I would vote labeling as "do not fix".

**Comment by arouinfar** [comment]
I agree @kathy-phet. Labelling as `type:wontfix`.
