### ISSUE TITLE
State Wrapper layering inconsistencies with ComboBox

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#293]
For https://github.com/phetsims/QA/issues/501. Found on ChromeOS.
In the state wrapper, there are inconsistencies between the layering in the top sim and the layering in the bottom sim. On the first and second screen, when using the drop down menu to switch between K and C, the layering with the thermometer is inconsistent. On the top the menu is above the thermometer. On the bottom, it is behind the thermometer.
![statelayering](https://user-images.githubusercontent.com/41024075/82584291-88eb4e00-9b51-11ea-9863-3635b5f3fb94.png)

**Comment by jbphet** [comment]
I believe that this is happening because the `visible` attribute of the list box associated with the `ComboBox` is be set to `true` through phet-io, but the method `ComboBox.showListBox` is *not* being called because the button listener wasn't fired.  I considered making a separate layer for the list box and passing it in to the `ComboBox` when it is constructed in `CompositeThermometerNode`, but this would only solve the problem for this particular case, so I went with a more general solution, which was to have code in `ComboBox` that listens to the `visibleProperty` of the list box and moves it to the front of the z-order when visible transitions to true.  

@pixelzoom - You're listed as the main author for `ComboBox`, so review.  My main concern here is that the list box can end up being shown without some of the other items in `showListBox` being called, but it seems to work fine when tested in both the "State" and "Studio" wrappers.  If you give it the thumbs down, I'll revert and create a separate layer for the list box.

**Comment by jbphet** [comment]
@arouinfar and I reviewed this on 5/29/2020 and we decided that it does not need to be fixed for an early customer dev release, but should be addressed before a fully phet-io release of this sim.

**Comment by pixelzoom** [comment]
Agreed that this should be fixed.  This is another case of having to retrofit code to accommodate PhET-iO restore.  It will undoubtedly make ComboBox more complicated. Not something I'm interested in working on, so assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
Also recommended to create an issue specific to ComboBox in the sun repo, so that it's clear that this affects all sims that use a ComboBox.  And so that the work required on ComboBox will be associated with that issue, instead of a sim-specific SOM issue.

**Comment by pixelzoom** [comment]
@jbphet said:
> ... you give it the thumbs down, I'll revert and create a separate layer for the list box.

By not providing a separate layer, you're currently exploiting behavior that may change in the future. All popups (include listbox) are designed to be in a separate layer, and that will certainly be the case if we ever get around to addressing this generally.  So if it were me, I'd revert the change and add the missing layer.

**Comment by pixelzoom** [comment]
Since I'm the primary author of ComboBox, this was on a list of issues that @ariel-phet and I discussed this morning.  Summary of our discussion:

* Since there's a question about whether the change that @jbphet made to ComboBox might have problems, and we don't have time to investigate, let's revert that change and use a separate layer in SOM.  (I see that @jbphet has already self-assigned - would you mind handling this?)

* Label for developer meeting and create a PSA about using a separate layer for listbox.  It's a bit more work, but is how ComboBox was intended to be used.  Here's an example for the PSA:

```js
class MyScreenView extends ScreenView {
  constructor() {
    super();
    const popupLayer = new Node();
    const comboBox = new ComboBox(..., popupLayer, ...);
    this.addChild( comboBox );
    this.addChild( popupLayer ); // popupLayer should be on top!
  }
}
```

**Comment by jbphet** [comment]
@pixelzoom - I've reverted the change to ComboBox where it popped the list box to the front and I've added a separate layer for the list box to `CompositeThermometerNode`.  Please have a look, make sure it looks cool, and unassign if so (and assign back to me with comments if not).

@KatieWoe - please test on master and, if all looks good, unassign and leave open so that we can make sure to test on the next release.

**Comment by pixelzoom** [comment]
👍 Looks great!

**Comment by KatieWoe** [comment]
The pressure gauge always seems to read 0 with no labels.
![pressure label gone](https://user-images.githubusercontent.com/41024075/84954219-351d4780-b0b2-11ea-886a-1633cfca7936.png)

**Comment by KatieWoe** [comment]
It looks like that was already there now that I look. Sorry for missing that. Combo box looks ok. @jbphet should I make a new issue?

**Comment by jbphet** [comment]
> @jbphet should I make a new issue?

Yes, please do.  This is unrelated to the layering.

**Comment by chrisklus** [comment]
from 06/18/20 dev meeting:

PSA from https://github.com/phetsims/states-of-matter/issues/293#issuecomment-645503226 was delivered. @zepumph and @jbphet recommended more documentation in ComboBox to explain the reasoning. We feel good about closing!
