### ISSUE TITLE
State Pressure reads 0 and has no units

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#297]
Found during https://github.com/phetsims/states-of-matter/issues/293. Occurs in https://github.com/phetsims/QA/issues/501
The pressure gauge on the bottom sim in the state wrapper reads 0 without atm and does not change with the pressure. This was seen on master on 6/17/2020 on Win 10 Chrome.
![pressure label gone](https://user-images.githubusercontent.com/41024075/84956437-6f88e380-b0b6-11ea-9ae7-8addc1bbd5c6.png)

**Comment by jbphet** [comment]
Interesting.  This appears to be due to the fact that the clock is not being run on the downstream sim in the state wrapper, and the `DialGaugeNode` class relies on being clocked.  I added code to explicitly set the state if the pressure value is changed due to a phet-io state setting operation, and that seems to work well.

@KatieWoe - I believe this is now fixed on master, please verify and, if it's good, unassign and leave open so that we can test on the next release.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by KatieWoe** [comment]
Looks fixed on https://github.com/phetsims/QA/issues/525
