### ISSUE TITLE
Studio molecules in scene buttons shift when text disappears

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#298]
For https://github.com/phetsims/QA/issues/508, but seems to be SOM rather than studio.
When using the visible property to remove the text that is on the buttons to change scenes, the molecule image shifts a bit when the text disappears.
![shiftingmolecule](https://user-images.githubusercontent.com/41024075/85170998-6ff6bb00-b22b-11ea-83e9-fa03a5a681ed.gif)

**Comment by jbphet** [comment]
@arouinfar - please weigh in and let me know if you think this is something that should be addressed and, if so, if it is blocking for the initial dev release to the customer.

**Comment by arouinfar** [comment]
@jbphet this is not critical to fix for the initial dev release. I wonder if this could be related to the dynamic layout when UI elements are removed. If I change the `textProperty` of the string to null, the layout is undisturbed.
![image](https://user-images.githubusercontent.com/8419308/85357924-aa808200-b4cf-11ea-9707-bdb635dd3737.png)

**Comment by arouinfar** [comment]
Actually, on second thought, I think the current behavior is fine.

The gif shows what happens when the `visibleProperty` of the string (e.g. argonText) is set to false. This is not featured, and there are other ways to hide this text. If the goal is to remove the entire radio button, then the `visibleProperty` of the radio button should be set to false. If the goal is to hide the name, its `textProperty` can be edited to be a null string. Neither of these methods cause layout issues.

@jbphet please feel free to close if you agree.

**Comment by jbphet** [comment]
Thanks.  I do agree.  Closing.
