### ISSUE TITLE
Move IO type toStateObject/fromStateObject to core types

### ISSUE THREAD

**Issue by samreid** [phetsims/states-of-matter#306]
Identified during review in https://github.com/phetsims/states-of-matter/issues/299.  While implementation Natural Selection, @pixelzoom recommended a pattern where IO types delegate to core types like so:

https://github.com/phetsims/natural-selection/blob/484118041bc07e5f5d01df8d572067be9b350f79/js/common/model/BunnyCountsIO.js#L15-L39

It looks like we could benefit from the same pattern here.  Will this change allow any `@public` attributes to become private?

UPDATE: I can see this pattern is applied in some types like MultipleParticleModelIO but not in others, like MoleculeForceAndMotionDataSetIO.

**Comment by jbphet** [comment]
The methods have now been moved.  I was wondering about why there was an `applyState` method in the `MultipleParticleModel` version of serialization but no such method in the `MoleculeForceAndMotionDataSet` case.  I had a discussion with the phet-io team on zoom, and they let me know that this is because there are different types of serialization, and these two classes use two different types of serialization, and therefore the differences are correct.  We did a real-time review of the code during this discussion and they said that it looks structurally correct, so I'm going to close.
