### ISSUE TITLE
2 deprecation warnings in the sim

### ISSUE THREAD

**Issue by zepumph** [phetsims/states-of-matter#310]
After a conversation with the dev team today, it was brought up that you can run the sim with `?deprecationWarnings` to see what code is being used that is deprecated. 

This sim shows two warnings that look like they would be very easy to fix:
```
Deprecation warning: Node.toImage() is deprecated, please use Node.rasterized() instead
deprecationWarning @ deprecationWarning.js:18
toImage @ Node.js:4338
PhaseChangesIcon @ PhaseChangesIcon.js:122
PhaseChangesScreen @ PhaseChangesScreen.js:33
(anonymous) @ states-of-matter-main.js:39
window.phet.joist.launchSimulation @ simLauncher.js:91
proceedIfReady @ simLauncher.js:113
(anonymous) @ simLauncher.js:132
load (async)
(anonymous) @ logo_png.js:5


Deprecation warning: MultiLineText is deprecated, please use RichText instead
 deprecationWarning @ deprecationWarning.js:18
  MultiLineText @ MultiLineText.js:28
  PhaseDiagramAccordionBox @ PhaseDiagramAccordionBox.js:171
  PhaseChangesScreenView @ PhaseChangesScreenView.js:270
  (anonymous) @ PhaseChangesScreen.js:46
  initializeView @ Screen.js:288
  (anonymous) @ Sim.js:818
  (anonymous) @ Sim.js:826
  setTimeout (async)

**Comment by jbphet** [comment]
Should be fixed, leaving open to test.  Note that I changed the usages of `\n` to `<br>` in all existing translations so that we could use `RichText` instead of `MultiLineText`, and we should make sure to publish to the website at the same time that we publish the upcoming phet-io version.

Note to self:
- [ ] Verify that translations look good after publishing to master.

**Comment by ariel-phet** [comment]
Looks like we will try to do https://github.com/phetsims/states-of-matter-basics/issues/31 in the near future so assigning back to @jbphet

**Comment by jbphet** [comment]
The deprecation warnings were fixed a while back, and both the phet and phet-io versions were published at the same time, so that helped the translations.  I spot checked some of them, and they looked good.  Since SOMB should be published shortly, I'll follow up in the issue related to that, and will close this one.
