### ISSUE TITLE
Unable to change text of molecules on third screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#331]
For https://github.com/phetsims/QA/issues/525.
Client request:
>Edit the name of each atom and molecule

The client request guide gives these properties to do this on the third screen:
`statesOfMatter.interactionScreen.view.atomsControlPanel.radioButtonGroup.adjustableAttraction.textProperty`
`statesOfMatter.interactionScreen.view.atomsControlPanel.radioButtonGroup.argon.textProperty`
`statesOfMatter.interactionScreen.view.atomsControlPanel.radioButtonGroup.neon.textProperty`
However, none of these exist. I was unable to find any other way of changing this text either.

![notext](https://user-images.githubusercontent.com/41024075/90062194-8b6ac900-dca4-11ea-96f1-cf773df627e6.png)

**Comment by jbphet** [comment]
There was a fairly long dialog about this on our phet-io channel.  I don't want to repeat it here, since it's a private channel.  @arouinfar was involved in the discussion, perhaps she'd be willing to summarize.

**Comment by jbphet** [comment]
@arouinfar - It *is* possible to change the text in the equivalent panel on the "Phase Changes" screen.  Below is a screenshot.  It seems to me that we should use the same pattern.  Agreed?

![image](https://user-images.githubusercontent.com/3082831/90073639-cf66c980-dcb6-11ea-8d8c-d5a700cd364d.png)

**Comment by jbphet** [comment]
@arouinfar and I discussed this, and we concluded that it's probably best if we don't allow the user to modify the text for the radio buttons in the atom selection panel for the "Atomic Interactions" screen.  The main reasons are:

+ These represent the behavior of specific atoms, so changing them could end up being quite misleading
+ The current customer has said that they don't intend to use this screen, or at least do any customization on it
+ In the standalone sim the text is more complex, since heterogeneous atom pairs are supported, so we should really take the time to design the customization thoughtfully if and when customers express an interest

With this in mind, @arouinfar is going to update the client guide to reflect this, and will then assign back to me so that I can make sure that version of the guide is used in the next release candidate.

**Comment by arouinfar** [comment]
Thanks for the summary @jbphet. I edited the client requests doc in the commit referenced above. Note that I will need to update it again once we figure out what to do about #332, but those edits are unrealted to this issue.

**Comment by jbphet** [comment]
I have updated the version of the client guide used in the 1.2 release branch.  While there may be more updates needed, this change should address this particular issue.

I'm going to mark as fixed and will have the verified in the next RC.  @KatieWoe - the verification for this issue will be to make sure that the incorrect phetioID values are no longer in the client guide.

**Comment by KatieWoe** [comment]
Looks ok in rc.2. Will reopen if something comes up
