### ISSUE TITLE
Phase diagram comes back when switching molecules

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#332]
For https://github.com/phetsims/QA/issues/525
Client request:
>Hide the phase diagram

However, if you switch molecules after this has been hidden, it comes back.

![phasecomesback](https://user-images.githubusercontent.com/41024075/90066354-d7207100-dcaa-11ea-8f2b-18a32bebe03e.gif)

**Comment by jbphet** [comment]
This is a tricky problem.  The code is designed to turn off the visibility of the phase diagram for adjustable attraction and then turn it back on for everything else.  The most obvious way around this is to have an explicit "showPhaseDiagramProperty" value that can be used to include or exclude the diagram so that the code is free to adjust the visibility itself.  Then we would probably make the visibility read-only in this case.

@arouinfar - how does that sound to you?  It will be an API change, but I think that's probably okay at this point.

**Comment by jbphet** [comment]
I have implemented a solution on master (not yet propagated to the 1.2 release branch), but I find it pretty distasteful.  It addresses the scenario that @KatieWoe describes above so that if the user hides the phase diagram in Studio and then launches the sim, the phase diagram will remain hidden.  However, it does this by creating a flag that is set in the case where the visibility is set during a phetio state setting period, and that seems awkward to me.

An alternative would be to have a separate property called `displayPhaseDiagram` property that is a distinct property in the view and can be used for this purpose.  It would have potentially confusing interactions with the `visible` attribute of the phase diagram, but may, in the end, be less confusing overall.

@zepumph - Can you please look at my initial solution (see the commit above) and let me know if you also feel that this is sub-optimal?
@arouinfar - Can you comment on the idea of adding a specific, separate property that controls whether the phase diagram should ever be shown?

**Comment by arouinfar** [comment]
I don't love the prospect of adding a separate `displayPhaseDiagram` property, but I could live with it. I think the interaction could be a little clunky if there are two places to interact with the visibility of the AccordionBox. Is it possible to use the approach taken for the `NeutralIndicatorNode` in https://github.com/phetsims/ph-scale/issues/102?

Once we settle this, I'll need to edit the client requests doc, because https://github.com/phetsims/phet-io-client-guides/commit/d47b8c6cbd5701e4ce9139d77550661271b6c90b is now out of date.

**Comment by zepumph** [comment]
I didn't spend enough time in PhaseChangesScreenView to actually come up with a solution, but hopefully this patch and the screenshot from studio will get us on the right track. You can create an instrumented visibleProperty and pass it into a Node. In that case, the Node.visibleProperty will be a linkedElement to the outside visibleProperty. Do you think that is the compromise needed here?

![image](https://user-images.githubusercontent.com/6856943/90179638-39847a80-dd5a-11ea-8557-f90df56131a1.png)

<details>

```diff
Index: js/phase-changes/view/PhaseChangesScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/phase-changes/view/PhaseChangesScreenView.js	(revision 6bca2e532656abad03f485a1ad94e1d06d4676c7)
+++ js/phase-changes/view/PhaseChangesScreenView.js	(date 1597347706044)
@@ -8,6 +8,7 @@
  * @author Aaron Davis
  */
 
+import BooleanProperty from '../../../../axon/js/BooleanProperty.js';
 import DerivedProperty from '../../../../axon/js/DerivedProperty.js';
 import ObservableArray from '../../../../axon/js/ObservableArray.js';
 import Property from '../../../../axon/js/Property.js';
@@ -111,7 +112,7 @@
 
     // control when the heater/cooler node is enabled for input
     Property.multilink(
-      [model.isPlayingProperty, model.isExplodedProperty],
+      [ model.isPlayingProperty, model.isExplodedProperty ],
       ( isPlaying, isExploded ) => {
         if ( !isPlaying || isExploded ) {
           heaterCoolerNode.interruptSubtreeInput(); // cancel interaction
@@ -268,9 +269,13 @@
     );
     this.addChild( moleculesControlPanel );
 
+    const myVisibleProperty = new BooleanProperty( true, {
+      tandem: tandem.createTandem( 'displayPhaseDiagramProperty' )
+    } );
     // add phase diagram - in SOM basic version by default phase diagram should be closed.
     model.phaseDiagramExpandedProperty.value = isPotentialGraphEnabled;
     this.phaseDiagramAccordionBox = new PhaseDiagramAccordionBox( model.phaseDiagramExpandedProperty, {
+      visibleProperty: myVisibleProperty,
       minWidth: PANEL_WIDTH,
       maxWidth: PANEL_WIDTH,
       right: moleculesControlPanel.right,
@@ -345,12 +350,12 @@
       }
 
       // don't show the phase diagram for adjustable attraction, since we need the space for other things
-      this.phaseDiagramAccordionBox.visible = this.displayPhaseDiagram && substance !== SubstanceType.ADJUSTABLE_ATOM;
+      this.phaseDiagramAccordionBox.visible = substance !== SubstanceType.ADJUSTABLE_ATOM;
     } );
 
     // Update layout based on the visibility and bounds of the various control panels and accordion boxes.
     Property.multilink(
-      [this.phaseDiagramAccordionBox.visibleProperty, moleculesControlPanel.boundsProperty],
+      [ this.phaseDiagramAccordionBox.visibleProperty, moleculesControlPanel.boundsProperty ],
       ( phaseDiagramVisible, moleculeControlPanelBounds ) => {
         if ( isPotentialGraphEnabled ) {
           interactionPotentialAccordionBox.top = moleculeControlPanelBounds.bottom + INTER_PANEL_SPACING;

```
</details>

**Comment by jbphet** [comment]
> You can create an instrumented visibleProperty and pass it into a Node. In that case, the Node.visibleProperty will be a linkedElement to the outside visibleProperty. Do you think that is the compromise needed here?

I don't think that addresses the issue at the core of this, it just renames the property.

**Comment by jbphet** [comment]
@arouinfar and I just discussed (over Zoom) how to approach this.  We both liked the idea of using a container node as was done for ph-scale in https://github.com/phetsims/ph-scale/issues/102, but it's a little more complicated in this case, since there are attributes of the contained node that need to be accessed in our case.  Still, it seems like a good way to go, so here's the plan:

- [ ] Add a node called `phaseDiagramContainer` and put `phaseDiagramAccordionBox` in it
- [ ] Add the visible property of the new node to the list of featured IDs
- [ ] Remove the visibility of the accordion box from the featured IDs
- [ ] Make the visibility of the accordion box read-only if possible so that clients are not inclined to mess with it

**Comment by jbphet** [comment]
@arouinfar - The work listed above is complete.  Can you please update the client guides based on these changes and let me know when you're done?

**Comment by arouinfar** [comment]
@jbphet this looks great in master. I've edited the client guides in the above commits.

**Comment by KatieWoe** [comment]
looks ok in rc.2. Will reopen if something comes up.
