### ISSUE TITLE
should this sim use nitroglycerin?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#50]
Two of the 4 atoms present in this sim (H,O) are specified in nitroglycerin (see Element). And it would be nice if this sim contributed the other 2 (Ne, Ar) back to nitroglycerin.  Instead, this sim is duplicating colors.

**Comment by jbphet** [comment]
I just spent a bit of time looking at this, and my initial impression is that using nitroglycerin in this sim would be fairly difficult.  There are several reasons, but the main two are:
- The model simulates the position of each atom separately, e.g. it doesn't have a water molecule in the model, it has a type that defines a water molecule's structure but it provides position data for each atom separately.  The nitroglycerin repository appears to work more at the level of a molecule, and the model would need to provide position and rotation information to map well to it.  Changing to the way of working would take a lot of time.
- The view isn't using Scenery nodes for each atom/molecule, it's using a canvas.

**Comment by jbphet** [comment]
Having made the two points above, I'd be fine with extracting the color data for the atoms from this repo, and would be glad to put Ne and Ar in there.  From what I understand, we are using our own colors for these two elements because there isn't as much agreement in the chemistry world on how to portray them as there is for the other elements.

@pixelzoom - in your opinion, is it worthwhile for SOM to use the same color values and to put these elements into nitroglycerin?

**Comment by pixelzoom** [comment]
@jbphet asked:
> is it worthwhile for SOM to use the same color values and to put these elements into nitroglycerin?

I think that's up to the chem team. Do they want colors to be reusable/fixable across all sims? Or are they OK with duplicating colors?  If they want to standardize on colors, then maybe they should be added to PhetColorScheme, then used in nitroglycerin.

**Comment by ycarpenterphet** [comment]
I don't think that it is worth adding Ne and Ar colors to PhetColorScheme and/or nitroglycerin, since there really isn't a standard or commonly-accepted color associated with either of these elements. 

We may want to get @emily-phet to weigh in on this as well, in case there's something on the horizon (sim-wise) that would make having an internal standard for these elements particularly useful, but there's certainly no pedagogical or disciplinary reason to do so.

**Comment by emily-phet** [comment]
Sounds right to me, I don't see anything on the horizon using Ne or Ar...or nitroglycerin.

**Comment by jbphet** [comment]
Based on input from the chem team, it doesn't sound like integration with the nitroglycerin repository is worth the effort.  Closing.

**Comment by pixelzoom** [comment]
It's not just the colors. It's also the relative sizes of the molecules.  But it sounds like there's no interest in this at the moment.

**Comment by pixelzoom** [comment]
Reopening.  

@emily-phet wrote:
>  I don't see anything on the horizon using Ne or Ar...or nitroglycerin.

Please clarify. nitroglycerin is a repository of reusable chemistry components. Every chem sim that I've worked on has used nitroglycerin. States Of Matter uses nitroglycerin.

@ycarpenterphet wrote:
> I don't think that it is worth adding Ne and Ar colors to PhetColorScheme and/or nitroglycerin, since there really isn't a standard or commonly-accepted color associated with either of these elements

Colors are not the only issue here. Atoms and molecules in nitroglycerin also render with the correct relative sizes.  By putting Ne and Ar in nitroglycerin now, we would know that those elements are used by some sim, and could address the color standardization issue when another sim needs those elements.  By not putting them in nitroglycerin, we will likely end up with different-looking atoms without realizing it.

@jbphet wrote:
> using nitroglycerin in this sim would be fairly difficult.

Please explain. Since you're already using O2 and H2O from nitroglycerin, why would it be more difficult to use Ne and Ar?  I would expect that getting atoms/molecules from different libs would be a potential maintenance problem.

**Comment by pixelzoom** [comment]
Btw... The reason I'm pushing this issue is that I inevitably end up being the developer who has generalize and migrate elements to nitroglycerin. So I think a better approach is to add elements the first time they are needed by a sim.  But I'll be happy to close this issue if @jbphet agrees to do the work for Ne and Ar when it's inevitably needed by another sim (e.g., Neon Lights and Other Discharge Lamps).

**Comment by ycarpenterphet** [comment]
With respect to Neon Lights + Other Discharge Lamps, even though Neon is one of the atoms used, the representations of the atoms in that sim are intentionally not distinguished by color or size, because its not a pedagogically relevant part of the representation (and would likely distract from the features of these atoms that we are trying to have students attend to).

Thinking about future HTML sims (either Java conversions or new), most I can envision will be using either generic atoms or atoms that would be more reactive (like the O, H, etc. already in nitroglycerin) - mayyyybe the new version of gas properties could use them, but even then, I suspect a generic 'heavy' and 'light' atom would be more appropriate.

That being said, if it is useful to have the relative size information (and already guaranteed color-blind tested and contrasting colors) included in a common code repository like nitroglycerin, there might be opportunities to reuse these down the road - it just won't be something we're likely to reuse often, since these elements don't get used much. It's more likely that they would be used as representative generic atoms than to actually represent Neon or Argon in the near future.

**Comment by jbphet** [comment]
I've gone ahead and added argon and neon to Element class in the nitroglycerin repo, and States of Matter (SOM) now extracts all atom colors and masses - including oxygen and hydrogen - from the Element class.  There are two issues that we should address before we're done with this:
+ SOM uses the van der Waals radius values for the atoms, and nitroglycerin uses the covalent radius.  These values are unfortunately not consistently proportionate.  I tried using the covalent radius values, and they aren't going to work for SOM (I can elaborate if needed).  My preferred solution would be to add the van der Waals radius as a field in the Element class so that it would contain both the covalent and van der Waals values, but I'd like to clear this with @pixelzoom before going for it.
+ Neon and argon don't have Pauling electronegativity values in the chart referenced in the Element.js file.  I'm not a chemist, so I'm not entirely sure why, but I noticed none of the noble gasses have them, so I think this is just the way that Pauling electronegativity values work.  I entered ```null``` for this value in Element.js, but I'm not sure if 0 or something else would be more appropriate.

Assigning to @pixelzoom to discuss next steps on this.

**Comment by jbphet** [comment]
I've sent off an email to the chem team to ask what they would suggest for electronegativity values for neon and argon.

**Comment by jbphet** [comment]
@amyh-phet said:
> As far as I am aware, there are no values for electronegativity of helium, neon, and argon using the Pauling scale (assuming the numbers are calculated using Pauling's method).   I would think undefined would be the best table entry if we want to stick with this scale.

> @emily-phet - What do you think?

...and @emily-phet responded with:
> "Undefined" sounds good to me. 

This doesn't necessarily mean that we should use Javascript's ```undefined``` value, but we should agree how to handle it and document it in the Element constructor.

**Comment by pixelzoom** [comment]
Re: elements that have no electronegativity
I see that you set electronegativity to `null` in these cases. I guess that's appropriate, since undefined is typically used for a JS property that has no definition, while null is used for a property that exists but doesn't have a known value. 

Re: covalent vs van der Waals radius
Probably best to consult with @jonathanolson on this, since he create Element.js.  If you do add something like `vanDerWaalsRadius`, then I recommend renaming `radius` to `covalentRadius`.

**Comment by jbphet** [comment]
I spoke with @jonathanolson, and he was fine with the idea of adding ```vanDerWaalsRadius``` as a property of Element.  I'll do this.  I'll also add some documentation about the electronegativity property and null values.

**Comment by jbphet** [comment]
Done, assigning to @pixelzoom to review.  https://github.com/phetsims/nitroglycerin/issues/9 will also be assigned to him at some point to verify that the changes didn't adversely affect other sims, so he might want to look at both at the same time.

**Comment by pixelzoom** [comment]
Inspected changes, looks good, closing.
