### ISSUE TITLE
dioxygen is labeled as oxygen - translation issue

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter#51]
Oxygen is an atom. Dioxygen is a molecule. I would expect chemistry teachers to complain about the presentation in the control panel below, which shows a dioxygen molecule labeled as oxygen.

![screenshot_476](https://cloud.githubusercontent.com/assets/3046552/6447173/7eedb21c-c0cd-11e4-8f16-e06a99bbf6ec.png)

**Comment by jbphet** [comment]
Labeling diatomic oxygen as "Oxygen" is consistent with the original Java sim, and I've never heard any complaints about it.  I just discussed it in person with @arouinfar and she believes this is a non-issue.  Closing for now, will reopen if we hear any objections after publication.

**Comment by ycarpenterphet** [comment]
This is one of those weird things about chemical nomenclature - O2 is pretty commonly referred to by chemists and chemistry texts as 'oxygen' (and this drives students crazy). Different instructors will deal with this differently, some preferring to use dioxygen, some using "oxygen gas" or "molecular oxygen" to indicate O2 and "oxygen atom" to refer to O. 

FYI - this seems to be better handled in languages other than English, which do not appear to use the same word even in common speech. This is why we currently have an issue (reported on Unfuddle) in the Java sim where a only single string "Oxygen" is offered up for translators, since it's shared across States of Matter (where it labels O2) and Atomic Interactions (where it labels atomic O), resulting in mistranslation in one of the two sims when there are two words (e.g. in French).

**Comment by pixelzoom** [comment]
@ycarpenterphet wrote:
> This is why we currently have an issue (reported on Unfuddle) in the Java sim where a only single string "Oxygen" is offered up for translators,

Does the HTML5 version support 2 different strings, or has the Java problem been ported?

**Comment by pixelzoom** [comment]
Reopening until @ycarpenterphet replies.

**Comment by ycarpenterphet** [comment]
I'm not sure whether the HTML5 version supports 2 distinct strings - @jbphet can you comment?

**Comment by pixelzoom** [comment]
The HTML5 version does not support 2 distinct strings. Both atomic-interactions and states-of-matter are using a single "Oxygen" string.  Relevant code:

states-of-matter-strings_en.json, line 20:
> "oxygen": "Oxygen",

AtomicInteractionsControlPanel, line 39:
> var oxygenString = require( 'string!STATES_OF_MATTER/oxygen' );

PhaseChangesMileculesControlPanel, line 35:
> var oxygenString = require( 'string!STATES_OF_MATTER/oxygen' );

SolidLiquidGassMoleculesControlPanel, line 28:
> var oxygenString = require( 'string!STATES_OF_MATTER/oxygen' );

**Comment by jbphet** [comment]
I have created a separate string for diatomic oxygen and am using it on the panels on the "States" and "Phase Changes" screens.  The original string, simply named "oxygen", is being used in the Atomic Interactions sim.  Closing.
