### ISSUE TITLE
Depth of potential well can get too deep on 'Interaction' tab

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#63]
This issue was originally reported in #60, but is being split out separately here.

@ycarpenterphet reports that the depth of the potential well gets too deep on the 'Interaction' tab, and goes under the graph axes.  The following screen capture shows the issue.

![ai-graph-1](https://cloud.githubusercontent.com/assets/3082831/6563164/903a383c-c664-11e4-93df-f48a77cd81b9.png)

This is what @ycarpenterphet says the max depth should look like:

![ai-graph-2](https://cloud.githubusercontent.com/assets/3082831/6563187/b4658b6c-c664-11e4-93e5-ac4401afcb2b.png)

**Comment by jbphet** [comment]
For future reference, here is a dev version that exhibits this issue: http://www.colorado.edu/physics/phet/dev/html/states-of-matter/1.0.0-dev.4/states-of-matter_en.html.

**Comment by jbphet** [comment]
There are two ways in which this could be addressed.  One is to scale the graph differently.  The other is to reduce the maximum value for the interaction strength in the "Adjustable Attraction" case.  The depth of the well is already pretty small for neon (see below), so I'm not sure it would be a good idea to change the scale of the graph.

![ai-neon-depth](https://cloud.githubusercontent.com/assets/3082831/6563414/a1a38806-c666-11e4-9eda-5d101b5f15eb.png)

**Comment by jbphet** [comment]
Assigning to @ycarpenterphet to finalize a decision about how to address this.  In addition to the two options mentioned above, it may be possible to change the layout such that the graph is a little larger.  And, of course, it's always possible just to leave it as is, since I'm not aware of anyone ever expressing dissatisfaction about the Java version.

**Comment by ycarpenterphet** [comment]
While I am ok with leaving this as-is, I think there is another advantage of adjusting this so that the bottom of the well is slightly shallower and avoids overlapping the graph.

There is a known issue with the Java sim (which has carried over to the HTML5) where the point marker on the graph blinks or flickers when the bottom of the well overlaps the graph axis.

This problem seems to go away when the well is adjusted to prevent overlap. I suggest we slightly reduce the maximum value for the adjustable attraction to avoid overlap, and see if this fixes both problems.

Reassigning to @jbphet.

**Comment by ycarpenterphet** [comment]
If we do slightly reduce the maximum value for the adjustable attraction, it should simultaneously fix issue #25. Tagging this here so that we remember that these two issues are directly related.

**Comment by ChandrashekarBemagoni** [comment]
Fixed in above commit. Assigning to @jbphet for verification

**Comment by jbphet** [comment]
Assigning to @phet-steele for verification.

**Comment by phet-steele** [comment]
The well is shallower!
